### ISSUE TITLE
Ranks error starting

### ISSUE THREAD

**Issue by howy7214** [MC-Prison/Prison#76]
If you are making a bug report, fill out the form below. If you are making a suggestion or something other than a bug report, then you may remove this boilerplate text.

### Which module are you submitting this issue for?
Ranks

### Describe the issue you are experiencing.
Include details such as what you did, what happened, and what you think should have happened.

Getting server error loading:
[16:22:52 INFO]: [Prison] Enabling Prison v3.1
[16:22:52 INFO]: [Prison] Using version adapter tech.mcprison.prison.spigot.compat.Spigot19
[16:22:52 INFO]:  _____      _                 
[16:22:52 INFO]: |  __ \    (_)                
[16:22:52 INFO]: | |__) | __ _ ___  ___  _ __  
[16:22:52 INFO]: |  ___/ '__| / __|/ _ \| '_ \
[16:22:52 INFO]: | |   | |  | \__ \ (_) | | | |
[16:22:52 INFO]: |_|   |_|  |_|___/\___/|_| |_|
[16:22:52 INFO]: Loading version 3.1 on platform SpigotPlatform...
[16:22:52 INFO]: | Prison | Enable start...
[16:22:52 INFO]: | Prison | Enabled Prison v3.1 in 99 milliseconds.
[16:22:52 INFO]: | Prison | Mines enable start...
[16:22:52 INFO]: | Prison | Loaded 7 mines
[16:22:52 INFO]: | Prison | Mines enable succeeded, in 58 milliseconds.
[16:22:52 INFO]: | Prison | Ranks enable start...
[16:22:52 ERROR]: Error occurred while enabling Prison v3.1 (Is it up to date?)
java.lang.NullPointerException: null
	at tech.mcprison.prison.ranks.data.RankPlayer.<init>(RankPlayer.java:64) ~[?:?]
	at tech.mcprison.prison.ranks.managers.PlayerManager.lambda$loadPlayers$0(PlayerManager.java:79) ~[?:?]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_161]
	at tech.mcprison.prison.ranks.managers.PlayerManager.loadPlayers(PlayerManager.java:79) ~[?:?]
	at tech.mcprison.prison.ranks.PrisonRanks.enable(PrisonRanks.java:114) ~[?:?]
	at tech.mcprison.prison.modules.ModuleManager.enableModule(ModuleManager.java:83) ~[?:?]
	at tech.mcprison.prison.modules.ModuleManager.registerModule(ModuleManager.java:57) ~[?:?]
	at tech.mcprison.prison.spigot.SpigotPrison.initModules(SpigotPrison.java:244) ~[?:?]
	at tech.mcprison.prison.spigot.SpigotPrison.onEnable(SpigotPrison.java:108) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-4bd94dc-fb414fe]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-4bd94dc-fb414fe]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot.jar:git-Spigot-4bd94dc-fb414fe]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot.jar:git-Spigot-4bd94dc-fb414fe]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot.jar:git-Spigot-4bd94dc-fb414fe]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]

Please help thank you

If there is anything else that you think will help us solve the problem, please tell us here.

**Comment by DylanFPS** [comment]
It’s possible that you need to delete your player files, as we made some changes to the format. We apologise for the inconvenience, and we aim to prevent problems like this with a new configuration system in Prison 3.2
