### ISSUE TITLE
PaperSpigot PlayerInteractEvent bug

### ISSUE THREAD

**Issue by weekendsama** [MC-Prison/Prison#79]
If you are making a bug report, fill out the form below. If you are making a suggestion or something other than a bug report, then you may remove this boilerplate text.

### Which module are you submitting this issue for?

Example: PaperSpiot Error  Prison v3.1

### Describe the issue you are experiencing.
[23:07:14] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to Prison v3.1
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:195) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.BlockRedstoneOre.a(BlockRedstoneOre.java:37) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.Entity.move(Entity.java:723) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:411) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_151]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.lang.IllegalArgumentException: No enum constant tech.mcprison.prison.internal.events.player.PlayerInteractEvent.Action.PHYSICAL
	at java.lang.Enum.valueOf(Unknown Source) ~[?:1.8.0_151]
	at tech.mcprison.prison.internal.events.player.PlayerInteractEvent$Action.valueOf(PlayerInteractEvent.java:72) ~[?:?]
	at tech.mcprison.prison.spigot.SpigotListener.onPlayerInteract(SpigotListener.java:115) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor135.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
	... 20 more

**Comment by DylanFPS** [comment]
This is most likely due to an incompatibility with PaperSpigot.

**Comment by DylanFPS** [comment]
This is an API problem. At this time we have no suggestions to offer you, but your better off waiting for @faizaand to respond as he knows the API inside and out. In the meantime, if there was a version of Prison 3 that worked on PaperSpgiot, use that and let us know which version works.

**Comment by faizaand** [comment]
The problem was that our version of the `Action` enum did not match up with Spigot's. Thanks for catching that! It should be fixed in the next update. I don't have a timeframe for that but maybe @DylanFPS can get it on the nightly build server, and you could start using it right away?

In any case, I'll close this for now.
