### ISSUE TITLE
Ranks Bug Report

### ISSUE THREAD

**Issue by Mattx8y** [MC-Prison/Prison#86]
I tried loading Prison, and I got this error message upon loading Ranks:

[18:27:01 INFO]: | Prison | Ranks enable start...
[18:27:01 ERROR]: Error occurred while enabling Prison v3.1 (Is it up to date?)
java.lang.NullPointerException: null
        at tech.mcprison.prison.ranks.data.RankPlayer.<init>(RankPlayer.java:64) ~[?:?]
        at tech.mcprison.prison.ranks.managers.PlayerManager.lambda$loadPlayers$0(PlayerManager.java:79) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_172]
        at tech.mcprison.prison.ranks.managers.PlayerManager.loadPlayers(PlayerManager.java:79) ~[?:?]
        at tech.mcprison.prison.ranks.PrisonRanks.enable(PrisonRanks.java:114) ~[?:?]
        at tech.mcprison.prison.modules.ModuleManager.enableModule(ModuleManager.java:83) ~[?:?]
        at tech.mcprison.prison.modules.ModuleManager.registerModule(ModuleManager.java:57) ~[?:?]
        at tech.mcprison.prison.spigot.SpigotPrison.initModules(SpigotPrison.java:244) ~[?:?]
        at tech.mcprison.prison.spigot.SpigotPrison.onEnable(SpigotPrison.java:108) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-21d5f75]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar:git-Spigot-2086bb0-21d5f75]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2.jar:git-Spigot-2086bb0-21d5f75]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot-1.12.2.jar:git-Spigot-2086bb0-21d5f75]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot-1.12.2.jar:git-Spigot-2086bb0-21d5f75]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot-1.12.2.jar:git-Spigot-2086bb0-21d5f75]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot-1.12.2.jar:git-Spigot-2086bb0-21d5f75]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot-1.12.2.jar:git-Spigot-2086bb0-21d5f75]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.2.jar:git-Spigot-2086bb0-21d5f75]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-2086bb0-21d5f75]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]

Does anyone know what's wrong? It won't let me use the ranks feature.

**Comment by SevenSlayy** [comment]
#81
