### ISSUE TITLE
Error occur while enabling Prison v3.1.1

### ISSUE THREAD

**Issue by fbafaro** [MC-Prison/Prison#87]
I'm getting the following error when I start my server with the latest version: Error occur while enabling Prison v3.1.1

09:46:49] [Server thread/INFO]: [m
[09:46:49] [Server thread/INFO]: [0;33;22m _____      _                 [m
[09:46:49] [Server thread/INFO]: [0;33;22m|  __ \    (_)                [m
[09:46:49] [Server thread/INFO]: [0;33;22m| |__) | __ _ ___  ___  _ __  [m
[09:46:49] [Server thread/INFO]: [0;33;22m|  ___/ '__| / __|/ _ \| '_ \[m
[09:46:49] [Server thread/INFO]: [0;33;22m| |   | |  | \__ \ (_) | | | |[m
[09:46:49] [Server thread/INFO]: [0;33;22m|_|   |_|  |_|___/\___/|_| |_|[m
[09:46:49] [Server thread/INFO]: [m
[09:46:49] [Server thread/INFO]: Loading version 3.1.1 on platform SpigotPlatform...[m
[09:46:49] [Server thread/INFO]: [0;30;1m| [0;36;22mPrison [0;30;1m| [0;37;1mEnable start...[m
[09:46:49] [Server thread/INFO]: [0;30;1m| [0;36;22mPrison [0;30;1m| [0;37;1mEnabled [0;36;22mPrison v3.1.1 in 110 milliseconds.[m
[09:46:50] [Server thread/INFO]: [0;30;1m| [0;36;22mPrison [0;30;1m| [0;37;1mMines enable start...[m
[09:46:50] [Server thread/INFO]: [0;30;1m| [0;36;22mPrison [0;30;1m| [0;37;1mLoaded 6 mines[m
[09:46:50] [Server thread/INFO]: [0;30;1m| [0;36;22mPrison [0;30;1m| [0;37;1mMines enable succeeded, in 97 milliseconds.[m
[09:46:50] [Server thread/INFO]: [0;30;1m| [0;36;22mPrison [0;30;1m| [0;37;1mRanks enable start...[m
[09:46:50] [Server thread/ERROR]: Error occurred while enabling Prison v3.1.1 (Is it up to date?)
java.lang.NullPointerException: null
	at tech.mcprison.prison.ranks.data.RankPlayer.<init>(RankPlayer.java:64) ~[?:?]
	at tech.mcprison.prison.ranks.managers.PlayerManager.lambda$loadPlayers$0(PlayerManager.java:79) ~[?:?]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_171]
	at tech.mcprison.prison.ranks.managers.PlayerManager.loadPlayers(PlayerManager.java:79) ~[?:?]
	at tech.mcprison.prison.ranks.PrisonRanks.enable(PrisonRanks.java:114) ~[?:?]
	at tech.mcprison.prison.modules.ModuleManager.enableModule(ModuleManager.java:83) ~[?:?]
	at tech.mcprison.prison.modules.ModuleManager.registerModule(ModuleManager.java:57) ~[?:?]
	at tech.mcprison.prison.spigot.SpigotPrison.initModules(SpigotPrison.java:244) ~[?:?]
	at tech.mcprison.prison.spigot.SpigotPrison.onEnable(SpigotPrison.java:108) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-c5afb9f-21d5f75]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-c5afb9f-21d5f75]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot.jar:git-Spigot-c5afb9f-21d5f75]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot.jar:git-Spigot-c5afb9f-21d5f75]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot.jar:git-Spigot-c5afb9f-21d5f75]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot.jar:git-Spigot-c5afb9f-21d5f75]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot.jar:git-Spigot-c5afb9f-21d5f75]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot.jar:git-Spigot-c5afb9f-21d5f75]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-c5afb9f-21d5f75]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot.jar:git-Spigot-c5afb9f-21d5f75]
	at java.lang.Thread.run(Unknown

**Comment by DylanFPS** [comment]
You may need to delete your rank player files to fix this.
